In [36]:
import scanpy as sc
import numpy as np
import pandas as pd
import decoupler as dc
from seq2cells.utils.anndata_utils import pseudo_bulk

In [37]:
pbmc_pred = sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells/tests/thymus_atlas_hsc_preprocessed_matched_out_largeemb_gpt4.h5ad")
#pbmc_pred = sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells/tests/HSC_thymus_atlas_hsc_emb_out_maxscale.h5ad")

In [38]:
# pbmc_pred.obs['ens_id'] = pbmc_pred.obs.index
# pbmc_pred.var['cell types'] = pbmc_pred.var.leiden.copy()

In [39]:
sampled_adata = sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells/tests/thymus_atlas_hsc_preprocessed_matched_out_largeemb_gpt4.h5ad")
# sampled_adata =  sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells_data/thymic_hsc/ct_data/HSC_thymus_atlas_hsc_emb_standardscale.h5ad")

In [40]:
# sampled_adata.X = sampled_adata.X.toarray()
# sampled_adata.obs['ens_id'] = sampled_adata.obs.index
# sampled_adata.var['cell types'] = sampled_adata.var.leiden.copy()

In [41]:
sampled_adata_test = sampled_adata[sampled_adata.obs['enf_set'] == 'test']
pbmc_pred_test = pbmc_pred[pbmc_pred.obs['enf_set'] == 'test']
pbmc_pred_test.X = pbmc_pred_test.layers['predicted']


/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/sparse/_index.py:137: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray_sparse(i, j, x)


In [42]:
sampled_adata_test.var['train'] = 'train'

/tmp/ipykernel_2833538/3919050578.py:1: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  sampled_adata_test.var['train'] = 'train'


In [43]:
pbmc_pred_test.var['cell types']

Cell_0        proB
Cell_1        T_DN
Cell_2         NMP
Cell_3        T_DN
Cell_4         ETP
              ... 
Cell_30689     HSC
Cell_30690     HSC
Cell_30691     Mgk
Cell_30692     Mgk
Cell_30693     NMP
Name: cell types, Length: 30694, dtype: category
Categories (10, object): ['ETP', 'Ery', 'HSC', 'MEMP', ..., 'NMP', 'T_DN', 'pDC', 'proB']

In [44]:
# list(sampled_adata_test.obs['gene_symbol'])

In [45]:
# sampled_adata_test = sampled_adata_test.T
sampled_adata_test.layers['x_raw'] = sampled_adata_test.X.copy()
sampled_adata_test = pseudo_bulk(sampled_adata_test,
            genes=list(sampled_adata_test.obs['ens_id']),
            cell_type_col='cell types',
            gene_col='ens_id',
            mode='mean',
            expr_threshold=0,
            mem_efficient_mode=True,
            layer='x_raw')

In [46]:
# sampled_adata_test = sampled_adata_test.T
pbmc_pred_test = pseudo_bulk(pbmc_pred_test,
            genes=list(pbmc_pred_test.obs['ens_id']),
            cell_type_col='cell types',
            gene_col='ens_id',
            mode='mean',
            expr_threshold=0,
            mem_efficient_mode=True,
            layer='predicted')

In [47]:
pbmc_pred_test.X

array([[0.11465588, 0.1738008 , 0.14024109, ..., 0.16068782, 0.1255637 ,
        0.10300833],
       [0.02151974, 0.03394121, 0.02285835, ..., 0.02157878, 0.02813705,
        0.01460992],
       [0.04048761, 0.03179123, 0.03538531, ..., 0.03068536, 0.04576844,
        0.02587532],
       ...,
       [0.42924938, 0.57186484, 0.43644163, ..., 0.5637991 , 0.52098215,
        0.46406525],
       [0.7031698 , 0.0599301 , 0.45401037, ..., 0.38819155, 1.6047225 ,
        1.1056019 ],
       [0.29955322, 0.40529296, 0.36763677, ..., 0.30565485, 0.60519177,
        0.47340828]], dtype=float32)

In [48]:
sampled_adata_test.X

array([[0.0000000e+00, 1.4113029e-03, 7.9970611e-03, ..., 2.1235421e-03,
        0.0000000e+00, 1.3166037e-02],
       [0.0000000e+00, 9.0268231e-04, 1.3769843e-03, ..., 6.0006429e-04,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [6.2871683e-01, 1.0952419e+00, 7.7299881e-01, ..., 7.2992748e-01,
        8.4153837e-01, 7.8994447e-01],
       [1.2279181e+00, 7.7171549e-02, 3.3349001e-01, ..., 1.2892584e+00,
        8.4509939e-01, 3.8339875e+00],
       [3.0363962e-01, 4.0780610e-01, 2.9970473e-01, ..., 3.0802226e-01,
        5.2305430e-01, 3.2122162e-01]], dtype=float32)

In [49]:
pbmc_pred_test.X

array([[0.11465588, 0.1738008 , 0.14024109, ..., 0.16068782, 0.1255637 ,
        0.10300833],
       [0.02151974, 0.03394121, 0.02285835, ..., 0.02157878, 0.02813705,
        0.01460992],
       [0.04048761, 0.03179123, 0.03538531, ..., 0.03068536, 0.04576844,
        0.02587532],
       ...,
       [0.42924938, 0.57186484, 0.43644163, ..., 0.5637991 , 0.52098215,
        0.46406525],
       [0.7031698 , 0.0599301 , 0.45401037, ..., 0.38819155, 1.6047225 ,
        1.1056019 ],
       [0.29955322, 0.40529296, 0.36763677, ..., 0.30565485, 0.60519177,
        0.47340828]], dtype=float32)

In [50]:
import scipy.stats
import sklearn.metrics
import numpy as np

In [51]:
r2_list = []
mse_list = []
for i,j in zip(pbmc_pred_test.X, sampled_adata_test.X):
    accdata = scipy.stats.pearsonr(i,j)[0]
    r2_list.append(accdata)
    mse_list.append(sklearn.metrics.mean_squared_error(i,j))

/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-pac

In [52]:
r2_list
print(np.nanmean(r2_list))
print(np.nanstd(r2_list))

0.4091817804175239
0.40404937804484886


In [53]:
mse_list
print(np.nanmean(mse_list))
print(np.nanstd(mse_list))

0.23581873
0.8326073


In [25]:
import pickle 
dict_data = {}
dict_data['corr'] = r2_list
dict_data['mse'] = mse_list
method = 'seq2cells2'
with open(f"{method}_thymus_hsc_hyenadna_result_ct_hsc_mixtureloss.pickle", "wb") as output_file:
    pickle.dump(dict_data, output_file)

In [54]:
r2_list = []
mse_list = []
for i,j in zip(pbmc_pred_test.X.T, sampled_adata_test.X.T):
    accdata = scipy.stats.pearsonr(i,j)[0]
    r2_list.append(accdata)
    mse_list.append(sklearn.metrics.mean_squared_error(i,j))

In [55]:
r2_list
print(np.nanmean(r2_list))
print(np.nanstd(r2_list))

0.7886421916432671
0.011463566299048072


In [56]:
mse_list
print(np.mean(mse_list))
print(np.std(mse_list))

0.23581874
0.032631196


In [29]:
import pickle 
dict_data = {}
dict_data['corr'] = r2_list
dict_data['mse'] = mse_list
method = 'seq2cells2'
with open(f"{method}_thymus_hsc_hyenadna_cell_result_ct_hsc_mixtureloss.pickle", "wb") as output_file:
    pickle.dump(dict_data, output_file)

In [1]:
import scanpy as sc
import numpy as np
import pandas as pd
import decoupler as dc
from seq2cells.utils.anndata_utils import pseudo_bulk

In [2]:
pbmc_pred = sc.read_h5ad("/home/tl688/project/seq2cells/tests/thymus_atlas_hsc_matched_with_precomp_embeddings_out_prop_0.8.h5ad")
#pbmc_pred = sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells/tests/HSC_thymus_atlas_hsc_emb_out_maxscale.h5ad")

In [4]:
sampled_adata = sc.read_h5ad("/home/tl688/project/seq2cells/tests/thymus_atlas_hsc_matched_with_precomp_embeddings_out_prop_0.8.h5ad")
# sampled_adata =  sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells_data/thymic_hsc/ct_data/HSC_thymus_atlas_hsc_emb_standardscale.h5ad")

In [5]:
sampled_adata

AnnData object with n_obs × n_vars = 14563 × 30694
    obs: 'gene_symbol', 'ens_id', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_expressed', 'chr', 'seq_start', 'seq_end', 'patch_id', 'center', 'num_roi', 'stretch', 'positions_roi', 'bins_roi', 'strands_roi', 'enf_set'
    var: 'Sample', 'donor', 'organ', 'sort', 'method', 'file', 'cell types', 'barcode'
    uns: 'Sample_colors', 'cell types_colors', 'donor_colors', 'hvg'
    obsm: 'seq_embedding'
    varm: 'X_umap'
    layers: 'predicted'

In [6]:
sampled_adata_test = sampled_adata[sampled_adata.obs['enf_set'] == 'test']
pbmc_pred_test = pbmc_pred[pbmc_pred.obs['enf_set'] == 'test']
pbmc_pred_test.X = pbmc_pred_test.layers['predicted']

/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/sparse/_index.py:137: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray_sparse(i, j, x)


In [7]:
sampled_adata_test.var['train'] = 'train'

/tmp/ipykernel_1802474/3919050578.py:1: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  sampled_adata_test.var['train'] = 'train'


In [8]:
pbmc_pred_test

View of AnnData object with n_obs × n_vars = 1391 × 30694
    obs: 'gene_symbol', 'ens_id', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_expressed', 'chr', 'seq_start', 'seq_end', 'patch_id', 'center', 'num_roi', 'stretch', 'positions_roi', 'bins_roi', 'strands_roi', 'enf_set'
    var: 'Sample', 'donor', 'organ', 'sort', 'method', 'file', 'cell types', 'barcode'
    uns: 'Sample_colors', 'cell types_colors', 'donor_colors', 'hvg'
    obsm: 'seq_embedding'
    varm: 'X_umap'
    layers: 'predicted'

In [9]:
# list(sampled_adata_test.obs['gene_symbol'])

In [10]:
# sampled_adata_test = sampled_adata_test.T
sampled_adata_test.layers['x_raw'] = sampled_adata_test.X.copy()
sampled_adata_test = pseudo_bulk(sampled_adata_test,
            genes=list(sampled_adata_test.obs['ens_id']),
            cell_type_col='cell types',
            gene_col='ens_id',
            mode='mean',
            expr_threshold=0,
            mem_efficient_mode=True,
            layer='x_raw')

In [11]:
# sampled_adata_test = sampled_adata_test.T
pbmc_pred_test = pseudo_bulk(pbmc_pred_test,
            genes=list(pbmc_pred_test.obs['ens_id']),
            cell_type_col='cell types',
            gene_col='ens_id',
            mode='mean',
            expr_threshold=0,
            mem_efficient_mode=True,
            layer='predicted')

In [12]:
pbmc_pred_test.X

array([[0.6787489 , 0.825554  , 0.7377155 , ..., 0.74258244, 0.7139426 ,
        0.7035035 ],
       [0.5058829 , 0.4749566 , 0.47880757, ..., 0.5149282 , 0.5412954 ,
        0.496977  ],
       [0.5142578 , 0.49575356, 0.49899015, ..., 0.51417994, 0.5461226 ,
        0.50343716],
       ...,
       [0.5187116 , 0.47579473, 0.5064283 , ..., 0.50718206, 0.5359494 ,
        0.50043887],
       [0.5022402 , 0.5232243 , 0.490988  , ..., 0.4985612 , 0.5178396 ,
        0.48349884],
       [0.5466488 , 0.5492477 , 0.55471796, ..., 0.5440376 , 0.52571404,
        0.5112357 ]], dtype=float32)

In [13]:
sampled_adata_test.X

array([[6.9267079e-02, 5.0787609e-02, 4.6880461e-02, ..., 6.0027827e-02,
        7.0645265e-02, 5.4909103e-02],
       [4.3045934e-03, 0.0000000e+00, 0.0000000e+00, ..., 4.3444679e-04,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [6.6660019e-03, 9.2466408e-03, 1.1690021e-03, ..., 2.1146117e-03,
        0.0000000e+00, 2.8779794e-02],
       [3.4674826e-01, 9.4336402e-03, 7.0214570e-02, ..., 2.3024883e+00,
        1.4239083e-01, 4.0873818e-02],
       [1.5225379e-02, 9.9021813e-04, 0.0000000e+00, ..., 8.7838592e-03,
        0.0000000e+00, 9.4471377e-04]], dtype=float32)

In [14]:
pbmc_pred_test.X

array([[0.6787489 , 0.825554  , 0.7377155 , ..., 0.74258244, 0.7139426 ,
        0.7035035 ],
       [0.5058829 , 0.4749566 , 0.47880757, ..., 0.5149282 , 0.5412954 ,
        0.496977  ],
       [0.5142578 , 0.49575356, 0.49899015, ..., 0.51417994, 0.5461226 ,
        0.50343716],
       ...,
       [0.5187116 , 0.47579473, 0.5064283 , ..., 0.50718206, 0.5359494 ,
        0.50043887],
       [0.5022402 , 0.5232243 , 0.490988  , ..., 0.4985612 , 0.5178396 ,
        0.48349884],
       [0.5466488 , 0.5492477 , 0.55471796, ..., 0.5440376 , 0.52571404,
        0.5112357 ]], dtype=float32)

In [15]:
import scipy.stats
import sklearn.metrics
import numpy as np

In [16]:
r2_list = []
mse_list = []
for i,j in zip(pbmc_pred_test.X, sampled_adata_test.X):
    accdata = scipy.stats.pearsonr(i,j)[0]
    r2_list.append(accdata)
    mse_list.append(sklearn.metrics.mean_squared_error(i,j))

/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-pac

In [17]:
r2_list

[0.07041645646381443,
 0.22719227431403533,
 nan,
 0.6195892764336421,
 -0.03310695101550431,
 0.9590500744515886,
 0.6774011415749914,
 0.37219466356172437,
 0.40525655229483293,
 0.48326229856376174,
 0.5012968983553274,
 0.5509246821478718,
 0.11180609596925893,
 0.4971942333714637,
 -0.3708327632048554,
 0.22756676954030644,
 0.7417687628547199,
 nan,
 0.961376243310255,
 0.7382757663227129,
 0.3070152940437944,
 0.6553599442015111,
 0.9684417019150698,
 0.35555620005417654,
 0.31371011173497654,
 0.8488363727019798,
 0.14860063508754087,
 0.819387828136084,
 0.18745899103361557,
 -0.10900717375692867,
 -0.022917521185893033,
 0.4391321085088371,
 -0.1714950170651507,
 0.8541638662288813,
 0.8566215609399999,
 0.9674327937239086,
 0.5192576143635788,
 -0.08650119364705794,
 0.48425773480805295,
 0.7217525860283138,
 0.4522436419056222,
 0.4244637324366011,
 0.8422392808923794,
 0.8030125654340075,
 0.7266953343208167,
 0.2628714407661863,
 0.7319859529445703,
 0.7022352116245083,
 

In [176]:
r2_list
print(np.nanmean(r2_list))
print(np.nanstd(r2_list))

0.42245034251830943
0.39940945130050626


In [177]:
mse_list
print(np.nanmean(mse_list))
print(np.nanstd(mse_list))

0.38789654
0.7474896


In [178]:
# import pickle 
# dict_data = {}
# dict_data['corr'] = r2_list
# dict_data['mse'] = mse_list
# method = 'seq2cells2'
# with open(f"{method}_thymus_hsc_hyenadna_result_ct_hsc_mixtureloss.pickle", "wb") as output_file:
#     pickle.dump(dict_data, output_file)

In [179]:
r2_list = []
mse_list = []
for i,j in zip(pbmc_pred_test.X.T, sampled_adata_test.X.T):
    accdata = scipy.stats.pearsonr(i,j)[0]
    r2_list.append(accdata)
    mse_list.append(sklearn.metrics.mean_squared_error(i,j))

In [180]:
r2_list
print(np.nanmean(r2_list))
print(np.nanstd(r2_list))

0.7827248471364587
0.011731348561683615


In [181]:
mse_list
print(np.mean(mse_list))
print(np.std(mse_list))

0.38789654
0.024457006


In [182]:
# import pickle 
# dict_data = {}
# dict_data['corr'] = r2_list
# dict_data['mse'] = mse_list
# method = 'seq2cells2'
# with open(f"{method}_thymus_hsc_hyenadna_cell_result_ct_hsc_mixtureloss.pickle", "wb") as output_file:
#     pickle.dump(dict_data, output_file)

In [27]:
import scanpy as sc
import numpy as np
import pandas as pd
import decoupler as dc
from seq2cells.utils.anndata_utils import pseudo_bulk

In [28]:
individual_level = "GTEx_v9_snRNAseq_data_GTEX-1ICG6_output.h5ad"

In [29]:
pbmc_pred = sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells/tests/individual/" + individual_level)
#pbmc_pred = sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells/tests/HSC_thymus_atlas_hsc_emb_out_maxscale.h5ad")

In [30]:
sampled_adata = sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells/tests/individual/" + individual_level)
# sampled_adata =  sc.read_h5ad("/gpfs/radev/project/ying_rex/tl688/seq2cells_data/thymic_hsc/ct_data/HSC_thymus_atlas_hsc_emb_standardscale.h5ad")

In [31]:
sampled_adata

AnnData object with n_obs × n_vars = 17333 × 20957
    obs: 'gene_ids', 'Chromosome', 'Source', 'Start', 'End', 'Strand', 'gene_name', 'gene_source', 'gene_biotype', 'gene_length', 'gene_coding_length', 'Approved symbol', 'Approved name', 'Status', 'Previous symbols', 'Alias symbols', 'gene_include', 'n_cells', 'enf_set'
    var: 'n_genes', 'fpr', 'tissue', 'prep', 'individual', 'nGenes', 'nUMIs', 'PercentMito', 'PercentRibo', 'Age_bin', 'Sex', 'Sample ID', 'Participant ID', 'Sample ID short', 'RIN score from PAXgene tissue Aliquot', 'RIN score from Frozen tissue Aliquot', 'Age', 'BMI', 'Race/Ethnicity', 'Autolysis Score', 'Sample Ischemic Time (mins)', 'Tissue Site Detail', 'scrublet', 'scrublet_score', 'barcode', 'batch', 'n_counts', 'tissue-individual-prep', 'Broad cell type', 'Granular cell type', 'introns', 'junctions', 'exons', 'sense', 'antisense', 'intergenic', 'batch-barcode', 'exon_ratio', 'intron_ratio', 'junction_ratio', 'log10_nUMIs', 'leiden', 'leiden_tissue', 'Tissue com

In [32]:
sampled_adata_test = sampled_adata[sampled_adata.obs['enf_set'] == 'test']
pbmc_pred_test = pbmc_pred[pbmc_pred.obs['enf_set'] == 'test']
pbmc_pred_test.X = pbmc_pred_test.layers['predicted']

/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/sparse/_index.py:137: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray_sparse(i, j, x)


In [33]:
sampled_adata_test.var['train'] = 'train'

/tmp/ipykernel_3519359/3919050578.py:1: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  sampled_adata_test.var['train'] = 'train'


In [34]:
pbmc_pred_test

View of AnnData object with n_obs × n_vars = 1740 × 20957
    obs: 'gene_ids', 'Chromosome', 'Source', 'Start', 'End', 'Strand', 'gene_name', 'gene_source', 'gene_biotype', 'gene_length', 'gene_coding_length', 'Approved symbol', 'Approved name', 'Status', 'Previous symbols', 'Alias symbols', 'gene_include', 'n_cells', 'enf_set'
    var: 'n_genes', 'fpr', 'tissue', 'prep', 'individual', 'nGenes', 'nUMIs', 'PercentMito', 'PercentRibo', 'Age_bin', 'Sex', 'Sample ID', 'Participant ID', 'Sample ID short', 'RIN score from PAXgene tissue Aliquot', 'RIN score from Frozen tissue Aliquot', 'Age', 'BMI', 'Race/Ethnicity', 'Autolysis Score', 'Sample Ischemic Time (mins)', 'Tissue Site Detail', 'scrublet', 'scrublet_score', 'barcode', 'batch', 'n_counts', 'tissue-individual-prep', 'Broad cell type', 'Granular cell type', 'introns', 'junctions', 'exons', 'sense', 'antisense', 'intergenic', 'batch-barcode', 'exon_ratio', 'intron_ratio', 'junction_ratio', 'log10_nUMIs', 'leiden', 'leiden_tissue', 'Tis

In [35]:
# list(sampled_adata_test.obs['gene_symbol'])

In [36]:
pbmc_pred_test.obs

gene_ids Chromosome          Source      Start        End  \
TNFRSF4     ENSG00000186827          1  ensembl_havana    1211325    1214138   
CPTP        ENSG00000224051          1  ensembl_havana    1324755    1328897   
RER1        ENSG00000157916          1  ensembl_havana    2391774    2405444   
PANK4       ENSG00000157881          1  ensembl_havana    2508532    2526628   
FAM213B     ENSG00000157870          1  ensembl_havana    2586490    2591469   
...                     ...        ...             ...        ...        ...   
PDZD4       ENSG00000067840          X  ensembl_havana  153802165  153830565   
BRCC3       ENSG00000185515          X  ensembl_havana  155071419  155123074   
MTCP1       ENSG00000214827          X  ensembl_havana  155061621  155147937   
RAB39B      ENSG00000155961          X  ensembl_havana  155258240  155264589   
AC006328.4  ENSG00000280301          Y         ensembl   25463993   25473714   

           Strand   gene_name     gene_source    gene_biotype  gene_length  \
TNFRSF4         -     TNFRSF4  ensembl_havana  protein_coding         2813   
CPTP            +        CPTP  ensembl_havana  protein_coding         4142   
RER1            +        RER1  ensembl_havana  protein_coding        13670   
PANK4           -       PANK4  ensembl_havana  protein_coding        18096   
FAM213B         +     FAM213B  ensembl_havana  protein_coding         4979   
...           ...         ...             ...             ...          ...   
PDZD4           -       PDZD4  ensembl_havana  protein_coding        28400   
BRCC3           +       BRCC3  ensembl_havana  protein_coding        51655   
MTCP1           -       MTCP1  ensembl_havana  protein_coding        86316   
RAB39B          -      RAB39B  ensembl_havana  protein_coding         6349   
AC006328.4      +  AC006328.4         ensembl  protein_coding         9721   

            gene_coding_length Approved symbol  \
TNFRSF4                   1721         TNFRSF4   
CPTP                      2556            CPTP   
RER1                      5691            RER1   
PANK4                     5107           PANK4   
FAM213B                   3371          PRXL2B   
...                        ...             ...   
PDZD4                     4341           PDZD4   
BRCC3                     3182           BRCC3   
MTCP1                     2990           MTCP1   
RAB39B                    3505          RAB39B   
AC006328.4                 501             nan   

                                                Approved name    Status  \
TNFRSF4                     TNF receptor superfamily member 4  Approved   
CPTP                    ceramide-1-phosphate transfer protein  Approved   
RER1        retention in endoplasmic reticulum sorting rec...  Approved   
PANK4                        pantothenate kinase 4 (inactive)  Approved   
FAM213B                                 peroxiredoxin like 2B  Approved   
...                                                       ...       ...   
PDZD4                                 PDZ domain containing 4  Approved   
BRCC3                BRCA1/BRCA2-containing complex subunit 3  Approved   
MTCP1                           mature T cell proliferation 1  Approved   
RAB39B                     RAB39B, member RAS oncogene family  Approved   
AC006328.4                                                nan       nan   

            Previous symbols                           Alias symbols  \
TNFRSF4               TXGP1L                      ACT35, OX40, CD134   
CPTP                  GLTPD1                                MGC10334   
RER1                     nan                                     nan   
PANK4                    nan                                FLJ10782   
FAM213B     C1orf93, FAM213B                                MGC26818   
...                      ...                                     ...   
PDZD4                  PDZK4  KIAA1444, LU1, FLJ34125, PDZRN4L, LNX5   
BRCC3                CXorf53               

In [37]:
# sampled_adata_test = sampled_adata_test.T
sampled_adata_test.layers['x_raw'] = sampled_adata_test.X.copy()
sampled_adata_test = pseudo_bulk(sampled_adata_test,
            genes=list(sampled_adata_test.obs['gene_ids']),
            cell_type_col='Broad cell type',
            gene_col='gene_ids',
            mode='mean',
            expr_threshold=0,
            mem_efficient_mode=True,
            layer='x_raw')

In [38]:
# sampled_adata_test = sampled_adata_test.T
pbmc_pred_test = pseudo_bulk(pbmc_pred_test,
            genes=list(pbmc_pred_test.obs['gene_ids']),
            cell_type_col='Broad cell type',
            gene_col='gene_ids',
            mode='mean',
            expr_threshold=0,
            mem_efficient_mode=True,
            layer='predicted')

In [39]:
pbmc_pred_test.X

array([[0.05628417, 0.04021012, 0.03824216, ..., 0.13153912, 0.03393642,
        0.03752175],
       [0.03278798, 0.02223021, 0.02091718, ..., 0.10110714, 0.01799712,
        0.02021961],
       [0.03840724, 0.02613026, 0.02498502, ..., 0.1066546 , 0.0211812 ,
        0.02365803],
       ...,
       [0.07852088, 0.05563186, 0.05206587, ..., 0.15161118, 0.05077563,
        0.05662224],
       [0.11187612, 0.08353986, 0.07895499, ..., 0.18458447, 0.07769199,
        0.08476167],
       [0.00942448, 0.00494953, 0.00418238, ..., 0.04040343, 0.00399212,
        0.00489605]], dtype=float32)

In [40]:
sampled_adata_test.X

array([[0.        , 0.09778246, 0.06798293, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.06364841, 0.05580503, ..., 0.        , 0.00183494,
        0.00796257],
       [0.0829743 , 0.08364321, 0.06971061, ..., 0.11761502, 0.07238388,
        0.08087704],
       ...,
       [0.        , 0.02660848, 0.0326831 , ..., 0.        , 0.07191955,
        0.10450552],
       [0.        , 0.        , 0.00137991, ..., 0.09774388, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [41]:
pbmc_pred_test.X

array([[0.05628417, 0.04021012, 0.03824216, ..., 0.13153912, 0.03393642,
        0.03752175],
       [0.03278798, 0.02223021, 0.02091718, ..., 0.10110714, 0.01799712,
        0.02021961],
       [0.03840724, 0.02613026, 0.02498502, ..., 0.1066546 , 0.0211812 ,
        0.02365803],
       ...,
       [0.07852088, 0.05563186, 0.05206587, ..., 0.15161118, 0.05077563,
        0.05662224],
       [0.11187612, 0.08353986, 0.07895499, ..., 0.18458447, 0.07769199,
        0.08476167],
       [0.00942448, 0.00494953, 0.00418238, ..., 0.04040343, 0.00399212,
        0.00489605]], dtype=float32)

In [42]:
import scipy.stats
import sklearn.metrics
import numpy as np

In [43]:
r2_list = []
mse_list = []
for i,j in zip(pbmc_pred_test.X, sampled_adata_test.X):
    accdata = scipy.stats.pearsonr(i,j)[0]
    r2_list.append(accdata)
    mse_list.append(sklearn.metrics.mean_squared_error(i,j))

/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4424: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
/home/tl688/.conda/envs/seq2cells/lib/python3.8/site-pac

In [44]:
r2_list
print(np.nanmean(r2_list))
print(np.nanstd(r2_list))

0.062089674092617814
0.3519482523679196


In [45]:
mse_list
print(np.nanmean(mse_list))
print(np.nanstd(mse_list))

0.04537205
0.17219847


In [46]:
import pickle 
dict_data = {}
dict_data['corr'] = r2_list
dict_data['mse'] = mse_list
method = 'seq2cells2'
with open(f"{individual_level}_individual_out.pickle", "wb") as output_file:
    pickle.dump(dict_data, output_file)

In [47]:
r2_list = []
mse_list = []
for i,j in zip(pbmc_pred_test.X.T, sampled_adata_test.X.T):
    accdata = scipy.stats.pearsonr(i,j)[0]
    r2_list.append(accdata)
    mse_list.append(sklearn.metrics.mean_squared_error(i,j))

In [48]:
r2_list
print(np.nanmean(r2_list))
print(np.nanstd(r2_list))

0.21344369801541063
0.05230365324101434


In [49]:
mse_list
print(np.mean(mse_list))
print(np.std(mse_list))

0.045372047
0.01732974


In [50]:
import pickle 
dict_data = {}
dict_data['corr'] = r2_list
dict_data['mse'] = mse_list
method = 'seq2cells2'
with open(f"{individual_level}_individual_cell_out.pickle", "wb") as output_file:
    pickle.dump(dict_data, output_file)

In [51]:
a = 1